from typing import TypeVar

__all__ = ["HINDERED_VISION_MODE", "UNHINDERED_VISION_MODE"]

HINDERED_VISION_MODE = TypeVar("HINDERED_VISION_MODE")
UNHINDERED_VISION_MODE = TypeVar("UNHINDERED_VISION_MODE")
